
	instance of MSFT_WebDownloadManager as $MSFT_WebDownloadManager1ref
	{
	ResourceID = "[ConfigurationRepositoryWeb]AzureAutomationDSC";
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::20::9::ConfigurationRepositoryWeb";
	 RegistrationKey = "2CgqSo5NKjJTDYNiczGcN9E53tbk7gLZw0MeYnFl+ET0Ld/rF11MSy+r36KcIRqZsQy5FzIWqkzzA2xTULEiZg=="; 
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/0ebd76be-11fc-446d-afae-727ef8601395";
	};

	instance of MSFT_WebResourceManager as $MSFT_WebResourceManager1ref
	{
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::27::9::ResourceRepositoryWeb";
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/0ebd76be-11fc-446d-afae-727ef8601395";
	 ResourceID = "[ResourceRepositoryWeb]AzureAutomationDSC";
	 RegistrationKey = "2CgqSo5NKjJTDYNiczGcN9E53tbk7gLZw0MeYnFl+ET0Ld/rF11MSy+r36KcIRqZsQy5FzIWqkzzA2xTULEiZg=="; 
	};

	instance of MSFT_WebReportManager as $MSFT_WebReportManager1ref
	{
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::34::9::ReportServerWeb";
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/0ebd76be-11fc-446d-afae-727ef8601395";
	 ResourceID = "[ReportServerWeb]AzureAutomationDSC";
	 RegistrationKey = "2CgqSo5NKjJTDYNiczGcN9E53tbk7gLZw0MeYnFl+ET0Ld/rF11MSy+r36KcIRqZsQy5FzIWqkzzA2xTULEiZg=="; 
	};

	instance of MSFT_DSCMetaConfiguration as $MSFT_DSCMetaConfiguration1ref
	{
	 RefreshMode = "Pull";
	 AllowModuleOverwrite = False;
	 ActionAfterReboot = "ContinueConfiguration";
	 RefreshFrequencyMins = 30;
	 RebootNodeIfNeeded = False;
	 ConfigurationModeFrequencyMins = 15;
	 ConfigurationMode = "ApplyAndMonitor";

	  ResourceModuleManagers = {
	  $MSFT_WebResourceManager1ref  
	};
	  ReportManagers = {
	  $MSFT_WebReportManager1ref  
	 };
	  ConfigurationDownloadManagers = {
	  $MSFT_WebDownloadManager1ref  
	 };
	};

	instance of OMI_ConfigurationDocument
	{
	 Version="2.0.0";
	 MinimumCompatibleVersion = "2.0.0";
	 CompatibleVersionAdditionalProperties= { "MSFT_DSCMetaConfiguration:StatusRetentionTimeInDays" };
	 Author="azureautomation";
	 GenerationDate="04/17/2015 11:41:09";
	 GenerationHost="azureautomation-01";
	 Name="RegistrationMetaConfig";
	};
	