
	instance of MSFT_WebDownloadManager as $MSFT_WebDownloadManager1ref
	{
	ResourceID = "[ConfigurationRepositoryWeb]AzureAutomationDSC";
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::20::9::ConfigurationRepositoryWeb";
	 RegistrationKey = "mupVVx7K3BNkdRAEqwXXe4gfjutPSUPoaXtd200Pr3cSNqWo1M6Edxji3ZxAvbFouHPS18wzjbZaNK82YZ45lQ=="; 
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/e5cdd34b-6cb0-47a7-9f95-51ea3a064915";
	};

	instance of MSFT_WebResourceManager as $MSFT_WebResourceManager1ref
	{
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::27::9::ResourceRepositoryWeb";
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/e5cdd34b-6cb0-47a7-9f95-51ea3a064915";
	 ResourceID = "[ResourceRepositoryWeb]AzureAutomationDSC";
	 RegistrationKey = "mupVVx7K3BNkdRAEqwXXe4gfjutPSUPoaXtd200Pr3cSNqWo1M6Edxji3ZxAvbFouHPS18wzjbZaNK82YZ45lQ=="; 
	};

	instance of MSFT_WebReportManager as $MSFT_WebReportManager1ref
	{
	 SourceInfo = "C:\\OaaS-RegistrationMetaConfig2.ps1::34::9::ReportServerWeb";
	 ServerURL = "https://eus2-agentservice-prod-1.azure-automation.net/accounts/e5cdd34b-6cb0-47a7-9f95-51ea3a064915";
	 ResourceID = "[ReportServerWeb]AzureAutomationDSC";
	 RegistrationKey = "mupVVx7K3BNkdRAEqwXXe4gfjutPSUPoaXtd200Pr3cSNqWo1M6Edxji3ZxAvbFouHPS18wzjbZaNK82YZ45lQ=="; 
	};

	instance of MSFT_DSCMetaConfiguration as $MSFT_DSCMetaConfiguration1ref
	{
	 RefreshMode = "Pull";
	 AllowModuleOverwrite = False;
	 ActionAfterReboot = "ContinueConfiguration";
	 RefreshFrequencyMins = 30;
	 RebootNodeIfNeeded = False;
	 ConfigurationModeFrequencyMins = 15;
	 ConfigurationMode = "ApplyAndMonitor";

	  ResourceModuleManagers = {
	  $MSFT_WebResourceManager1ref  
	};
	  ReportManagers = {
	  $MSFT_WebReportManager1ref  
	 };
	  ConfigurationDownloadManagers = {
	  $MSFT_WebDownloadManager1ref  
	 };
	};

	instance of OMI_ConfigurationDocument
	{
	 Version="2.0.0";
	 MinimumCompatibleVersion = "2.0.0";
	 CompatibleVersionAdditionalProperties= { "MSFT_DSCMetaConfiguration:StatusRetentionTimeInDays" };
	 Author="azureautomation";
	 GenerationDate="04/17/2015 11:41:09";
	 GenerationHost="azureautomation-01";
	 Name="RegistrationMetaConfig";
	};
	